#pragma once

#if defined(WIN32) || defined(_WIN32) || defined(__WIN32__)
#define COLOR_RESET     ""
#define COLOR_GRAY      ""
#define COLOR_ORANGE    ""
#define COLOR_GREEN     ""
#define COLOR_PURPLE    ""
#define COLOR_RED       ""
#define COLOR_DARK_RED  ""
#define EMOJI_SMILE     ""
#define EMOJI_WARNING   ""
#define EMOJI_ERROR     ""
#define EMOJI_FATAL     ""
#define EMOJI_OK        ""
#define EMOJI_DEBUG     ""
#define EMOJI_LEXER     ""
#define EMOJI_PARSER    ""
#define EMOJI_TREE      ""
#define EMOJI_BRAIN     ""
#define EMOJI_CODEGEN   ""
#define EMOJI_LINKER    ""
#define EMOJI_RUN       ""
#define EMOJI_DEVIL     ""
#define EMOJI_ALERT     ""
#else
#define COLOR_RESET     "\033[0m"
#define COLOR_GRAY      "\033[90m"
#define COLOR_ORANGE    "\033[38;5;208m"
#define COLOR_GREEN     "\033[32m"
#define COLOR_PURPLE    "\033[35m"
#define COLOR_RED       "\033[91m"
#define COLOR_DARK_RED  "\033[31m"
#define EMOJI_SMILE     "😄"
#define EMOJI_WARNING   "⚠️"
#define EMOJI_ERROR     "❌"
#define EMOJI_FATAL     "💥"
#define EMOJI_OK        "✅"
#define EMOJI_DEBUG     "🐛"
#define EMOJI_LEXER     "🔤"
#define EMOJI_PARSER    "🧩"
#define EMOJI_TREE      "🌳"
#define EMOJI_BRAIN     "🧠"
#define EMOJI_CODEGEN   "⚙️"
#define EMOJI_LINKER    "🔗"
#define EMOJI_RUN       "🚀"
#define EMOJI_DEVIL     "😈"
#define EMOJI_ALERT     "🚨"
#endif

extern const char* logLevelTags[];
extern const char* logCatagTags[];
